### ISSUE TITLE
Do you need sys in http-trigger-dump-request?

### ISSUE THREAD

**Issue by baizini** [yokawasa/azure-functions-python-samples#1]
Why do you need to import sys in http-trigger-dump-request?
The code seems to run fine without it.

**Comment by yokawasa** [comment]
@baizini  You're right. It's not needed. I'll remove importing sys from the code shortly. Thanks!

**Comment by yokawasa** [comment]
Now it's removed

https://github.com/yokawasa/azure-functions-python-samples/commit/cd8a70c12dcfc9422d1eb030fe0533f3e0bd286b
