### ISSUE TITLE
Extract a compressed file within azure blob

### ISSUE THREAD

**Issue by suntracks** [yokawasa/azure-functions-python-samples#10]
Would be great if there is a function to extract compressed files within azure blob.
Could not find any ready or work around solution to do this.

What is the best way it can acheived as of today.

**Comment by yokawasa** [comment]
@suntracks 
I've added a sample BlobTrigger function which does:
- Open Zipped file (that has ".zip" extension)
- Read files packed in the zipped file
- Print the clear text in the files packed in Zipped file 

https://github.com/yokawasa/azure-functions-python-samples/tree/master/blob-trigger-blob-in-out-bindings/function_zip

Hope it would help

**Comment by yokawasa** [comment]
@suntracks  Can you explain a bit more about your scenario? 

When it comes to blob file path or blob file name, in python code, you can NOT get the blob name in the Blob Trigger function. Instead, you need to use another mechanism to trigger the blob processing, such as a queue message that contains the blob name.

**Comment by yokawasa** [comment]
@suntracks  
I'm closing the issue. Please reopen if you have further question.

**Comment by hurtn** [comment]
Hi Yokawasa, thank you for sharing this code. I'm curious, do you need have another blob trigger function (probably not written in Python)  which inserts a message into the queue which then your python trigger can consume and obtain the blob file name from the queue?
