### ISSUE TITLE
When you add a function now - in the portal the quick start page has no Python options

### ISSUE THREAD

**Issue by djburnham** [yokawasa/azure-functions-python-samples#11]
In the latest incarnation of the portal UI quick start - which appears when you press the + sign to create a function there is no option to select 'experimental' languages like Python ! It looks like its C# or NodeJS only !

This sort-of breaks the whole point of this tutorial

**Comment by yokawasa** [comment]
@djburnham

Thanks for posting this.
This is because Azure function 2.0 became default runtime in Portal. If you switch the runtime to 1.X in Portal, you’ll see options to experimental languages. 
I’ll update this tutorial pretty soon and also add contents for Azure functions 2.0 Python.

**Comment by sweetmoniker** [comment]
Is soon > 6 months? It took me over an hour to find this.

**Comment by yokawasa** [comment]
@djburnham @sweetmoniker 
Very sorry for the late response. We are no longer able to create 1.X Python function in the Azure Portal. I suggest to create 2.X Python function. Here is a quickstart doc I created: 
- https://github.com/yokawasa/azure-functions-python-samples/blob/master/docs/quickstart-v2-python-functions.md 

Also this below is a note that I added to README.md of this project:
> - By default, function apps created in the Azure portal are set to version 2.x. When possible, you should use this runtime version, where new feature investments are being made. Please see [this](https://docs.microsoft.com/en-us/azure/azure-functions/functions-versions) for more detail on Azure Function runtime versions and supported languages
> - Please consider to use 2.X Python funciton as Python function in Azure function 1.X is experimental and new feature investments won't be added to 1.X Python function.

**Comment by yokawasa** [comment]
I'm closing this but please feel free to re-open the issue if you want to have further discussion.

For development of Python functions on Azure Functions 2.X,  please use the [Azure Functions Core Tools](https://docs.microsoft.com/en-us/azure/azure-functions/functions-create-first-function-python) or [VS Code extension](https://code.visualstudio.com/tutorials/functions-extension/getting-started).
