### ISSUE TITLE
How to use Timer output

### ISSUE THREAD

**Issue by Chenguoqing2008** [yokawasa/azure-functions-python-samples#17]
Thank you  for sharing these code samples of using azure functions.   I am learning how to use it now it is helpful.  I have one concern today of how to add input and output in Timer function.  From the official document [function reference](https://docs.microsoft.com/en-us/azure/azure-functions/functions-reference#fileupdate) I read that "Input" and "Output" bindings seem to be not allowed in Timer functions.

> **Bindings**
> Type  | 1.x | 2.x1 | Trigger | Input | Output|
> Timer | ✔ | ✔ | ✔        |  --     | --       | 

I also spent some time to research the material on the web and think a workaround to reloved this. This is because my project manager ask me to move the VM script to azure functions.

When i saw your [code example of Timer ](https://github.com/yokawasa/azure-functions-python-samples/blob/master/v1functions/timer-trigger-azuresearch-index-monitoring/function/function.json) i think maybe this is what i want. But, can you explain this to me?

```
{
      "type": "documentDB",
      "name": "outputDocument",
      "databaseName": "functions2docdb",
      "collectionName": "indexstats",
      "createIfNotExists": true,
      "connection": "<Connection string for your documentdb account>",
      "direction": "out"
    }

```

How can you use the `"direction": "out"`? This usage seems contrdict to the Microsoft azure functions document usage. 

Thanks.

**Comment by yokawasa** [comment]
@Chenguoqing2008 
You can configure output binding with Timer Trigger without any tricks. Here are references:
- CosmosDB output binding for V1 functions: https://docs.microsoft.com/en-us/azure/azure-functions/functions-bindings-cosmosdb
- CosmosDB output binding for V2 functions: https://docs.microsoft.com/en-us/azure/azure-functions/functions-bindings-cosmosdb-v2

By the way, which version are you going to use- V1 or V2?

**Comment by yokawasa** [comment]
@Chenguoqing2008 
FYI

I added V2 Function Timer Tigger sample: 
https://github.com/yokawasa/azure-functions-python-samples/tree/master/v2functions/timer-trigger-cosmosdb-output-binding

Hope it would help

**Comment by Chenguoqing2008** [comment]
@yokawasa I am using Azure functions V2.  Since your code is workable.  Why MicroSoft did document the Timer trigger as this?

> Bindings
> Type | 1.x | 2.x1 | Trigger | Input | Output|
> Timer | ✔ | ✔ | ✔ |  -- | -- |

This bring me a lot of confusing.

**Comment by Chenguoqing2008** [comment]
That's great. Thanks.
