### ISSUE TITLE
Writing to Azure Table Storage

### ISSUE THREAD

**Issue by W7PEA** [yokawasa/azure-functions-python-samples#2]
Do you happen to have an example of writing to Azure Table Storage?

**Comment by yokawasa** [comment]
Here is an example of writing to Azure Table Storage using Storage binding

https://github.com/yokawasa/azure-functions-python-samples/blob/master/eventhub-trigger-table-out-bindings/function/run.py

Please also refer to this for the detail of storage table binding:
https://docs.microsoft.com/en-us/azure/azure-functions/functions-bindings-storage-table

Hope it would help

**Comment by W7PEA** [comment]
I never would have guessed or derived from the samples which have full support to write to the binding name as if it was a file... 

Thank you Yoichi!

**Comment by yokawasa** [comment]
@W7PEA  Thanks. I understand. That's great feedback.
