### ISSUE TITLE
blob-in blob-out sample

### ISSUE THREAD

**Issue by snobu** [yokawasa/azure-functions-python-samples#20]
Is there interest for a blob triggered, image watermarking sample?
```
Blob trigger -> input blob (image) -> watermarking with Pillow -> output blob (image)
```
I see no *blob output as binary* sample, and it's not very obvious how typing works for that case.

I can send a PR if the outlook is positive here.

**Comment by yokawasa** [comment]
@snobu Sounds great!  PR is always welcome

**Comment by snobu** [comment]
PR sent, https://github.com/yokawasa/azure-functions-python-samples/pull/21.

**Comment by yokawasa** [comment]
@snobu  Thanks alot for sending PR! Really awesome sample!
