### ISSUE TITLE
Kudu tools not opening

### ISSUE THREAD

**Issue by bsnithin44** [yokawasa/azure-functions-python-samples#23]
Hi @yokawasa 

The hyperlink in platform features to kudu tools is not responding and also
https://(your-function-app-name).scm.azurewebsites.net/ is not working.

Do you know what could be the reason?

its python function app

Thank you

**Comment by yokawasa** [comment]
@bsnithin44 
Are you using Linux Consumption plan?  There is no Kudu site on Linux Consumption plan. I don't know the reason.

**Comment by bsnithin44** [comment]
@yokawasa 
Yes, I am using Linux Consumption plan.

I need to perform the following operation for opencv to work.

apt update && apt install -y libsm6 libxext6


Do you know any workaround for this?
Thank you

**Comment by snobu** [comment]
You can't `apt install` straight onto the worker. Build a docker image instead and install packages via Dockerfile. See this - https://github.com/Azure/azure-functions-docker-python-sample

Example:
```
# Dockerfile snippet

RUN apt-get update && apt install -y \
    libsm6 \
    libxext6
```

**Comment by bsnithin44** [comment]
But building a docker image will be only for app service plan right?. I am aware that we can do with docker.

I just wanted to know if there is any way to do it while using Consumption plan and CODE instead of docker image

**Comment by snobu** [comment]
That's correct, right now a dedicated plan is required for custom images.

**Comment by yokawasa** [comment]
> @bsnithin44 
In summary, running custom images as well as Kudu site is not supported in Linux Consumption plan.  Suggestions here are to use App service plan or try to use other libraries if possible to achieve the same goal that you could with OpenCV as @snobu commented above. 

I'm closing this but please feel free to re-open if you need further discussion
