### ISSUE TITLE
examples of output binding to service bus queue

### ISSUE THREAD

**Issue by alexgman** [yokawasa/azure-functions-python-samples#25]
Is there a way to read/write from service bus queue using python? I know there might not be a way to using an explicit binding, but perhaps there's a manual way where we establish a connection and manually put a message on a service bus queue? My main interest is in triggering with servicebus and then output to servicebus

**Comment by snobu** [comment]
Just `func new` and pick the Service Bus template. Do you mean there's no output binding for Service Bus in the runtime?

**Comment by alexgman** [comment]
correct, there's no output binding

**Comment by snobu** [comment]
Use a storage queue output binding for your main function and create a second function that triggers on that storage queue and writes to Service Bus using the storage SDK. This way once there's a Service Bus output binding you only need to change configuration, not code.

From 
https://docs.microsoft.com/en-us/azure/service-bus-messaging/service-bus-python-how-to-use-queues#send-messages-to-a-queue -

```
from azure.servicebus import QueueClient, Message

# Create the QueueClient
queue_client = QueueClient.from_connection_string(
    "<CONNECTION STRING>", "<QUEUE NAME>")

# Send a test message to the queue
msg = Message(b'Test Message')
queue_client.send(msg)
```

Don't forget to add `azure.servicebus` to your function app's `requirements.txt`.

**Comment by snobu** [comment]
Wait, judging by [**this**](https://github.com/Azure/azure-functions-python-worker/issues/447#issuecomment-516369422) there **is** an output binding for Service Bus. Try that first.

**Comment by snobu** [comment]
This PR (https://github.com/yokawasa/azure-functions-python-samples/pull/26) adds a sample for Service Bus trigger and output. I've tested it, works fine, the message gets added to the output Service Bus queue successfully.

**Comment by yokawasa** [comment]
@alexgman  We close the issue ( See PR #26).  Please feel free to open if you need further discussion!
