### ISSUE TITLE
Python Singleton instance for MongoDb

### ISSUE THREAD

**Issue by antonioschaffert** [yokawasa/azure-functions-python-samples#30]
Hi,

How do we create one MongoDb Connection to be used across all azure function invocations?

**Comment by yokawasa** [comment]
@antonioschaffert 
I believe this is a relevant issue. please take a look
https://github.com/Azure/azure-functions-host/issues/912

**Comment by yokawasa** [comment]
@antonioschaffert  I'm closing the issue. But please feel free to open if you need further discussion
