### ISSUE TITLE
Azure functions || python httptrigger || client before deployment || error posting file 

### ISSUE THREAD

**Issue by ElanReep** [yokawasa/azure-functions-python-samples#31]
error 
[12/09/2019 15:25:33] Error writing message type InvocationRequest to workerId: 44de9e70-9290-4fcb-a8e2-0a5d188e2f9a
[12/09/2019 15:25:33] System.Private.CoreLib: Error sending from server.

Post req from postman with File Key imgfile includeded in body - getting server error and the req never gets to the function
#####################

import logging
import azure.functions as func

def main(req: func.HttpRequest) -> func.HttpResponse:
    
    logging.info('Python HTTP trigger function processed a request.')

    decodeType = req.form['decodeType']
    
    imgfile = req.files['imgfile']

#####.......#######

**Comment by yokawasa** [comment]
@ElanReep 
First of all, please read this. You can find a workaround using base64 as well. 
- https://github.com/Azure/azure-functions-python-worker/issues/380

Secondly,  file uploading to httptrigger may cause unexpected timeout issues as it may be long-running. Please read this. You can find a workaround. 
- https://github.com/yokawasa/azure-functions-python-samples/issues/19#issuecomment-478322125
