### ISSUE TITLE
Question: Is it safe/okay to pip freeze > requirements.txt pinning the azure-functions version?

### ISSUE THREAD

**Issue by predatorian3** [yokawasa/azure-functions-python-samples#37]
Is it okay to:

```bash
python -m pip freeze > requirements.txt
```

the Python packages installed during development and pinning the `azure-functions` version? I'm not clear if Azure Functions will read that file and install the dependencies listed in that file.

**Comment by yokawasa** [comment]
@predatorian3  
Yes, you can. Dependencies are obtained remotely based on the contents of the `requirements.txt` file.
Please read this for more detail:
- https://docs.microsoft.com/en-us/azure/azure-functions/functions-reference-python#package-management

My recommendation is to include only minimum packages in `requirements.txt`.

**Comment by yokawasa** [comment]
@predatorian3 
I'm closing this but please feel free to open issue if you need further discussion
