### ISSUE TITLE
test and Trigger is not working 

### ISSUE THREAD

**Issue by mkhazen** [yokawasa/azure-functions-python-samples#42]
Hello 
when I test this and I try the 
HTTP Request body to include the following parameters:

{
    'permission': '<Signed permission for shared access signature (Required)>',
    'container': '<Container name to access (Required)>',
    'blobname': '<Blob object name to access (Optional)>'
    'ttl': '<Token time to live period in hours. 1hour by default (Optional)>'
}

I get the following errors 

Invalid blob path specified : '{"body":" {'permission': \"rwl\",\r\n 'container': \"sample-workitems\logomalek.jpg",\r\n 'ttl': 2\r\n }"}'. Blob identifiers must be in the format 'container/blob'.

please can you let us know what should we do? i am testing with python 3.7 - Azure function v2

**Comment by yokawasa** [comment]
@mkhazen 
if you want to specify blob file name, you need send a request body like this: 
```
{"body":" {'permission': "rwl",
 'container': "sample-workitems",  'blobname': "logomalek.jpg",
 'ttl': 2
 }"}
```
You need to specify container name and blob file name with `container` and `blobname` field respectively
Please try again and let me know how it will work

**Comment by yokawasa** [comment]
@mkhazen I'll close the issue but please feel free to open an issue if you have any other issue
