### ISSUE TITLE
Writing json to Azure Table Storage throws type error

### ISSUE THREAD

**Issue by hmqgg** [yokawasa/azure-functions-python-samples#7]
https://github.com/yokawasa/azure-functions-python-samples/blob/ce9ef7a04afa429e1655e2a75a2ec1acf52e9909/eventhub-trigger-table-out-bindings/function/run.py#L46

When I use `json.dump(somejson, f)`, it throws 
`TypeError: a bytes-like object is required, not 'str'`.

And if I use `json.dumps(somejson, f)`, it throws
`Microsoft.Azure.WebJobs.Host: Object reference not set to an instance of an object.`

It should be
```python
with open(os.environ['someTable'], 'w') as f:
    json.dump(somejson, f);
```

**Comment by yokawasa** [comment]
@hmqgg thank you for the feedback. 
as you suggested, I modified the mode from binary to text in opening output table:
https://github.com/yokawasa/azure-functions-python-samples/commit/c189c9c4b5d5bddb173338f1200d8a0d94eb3076

Thanks alot
