### ISSUE TITLE
One thing I woluld like to know that about azure functions by written python3

### ISSUE THREAD

**Issue by LenKIM** [yokawasa/azure-functions-python-samples#9]
First of all, Thank you for my PR.

At this moment, I wolud like to make automatically python crawler application included http.
But, I don't know how to use Azure function effiently

As your repository, 'https://github.com/yokawasa/azure-functions-python-samples/tree/master/blob-trigger-blob-in-out-bindings' mention that using blob storage seems like possible.

why I need blob storage is that I would like make .csv files from python3 files then I stores those .csv files to Blob storage

How can I solve this problem??

Again, I would like make the process automatically crawer written by pyhton3 with Azure functions. What is the most effient way to make the process ? 

Thank you.

**Comment by yokawasa** [comment]
@LenKIM  
Sorry for the delay. 

As you know, default Python platform version that Azure Functions support is Python 2.7.X. Here is a document on how to change the python version that I added before.  
https://github.com/yokawasa/azure-functions-python-samples/blob/master/docs/custom-python-version.md
Hope it would help

**Comment by LenKIM** [comment]
Thanks you for my Question.
